name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        echo "Installing dependencies..."
        pip install -r requirements.txt

    - name: Freeze the Flask app
      run: |
        source venv/bin/activate
        echo "Freezing the Flask application..."
        python freeze.py
        echo "Freeze complete."

    - name: List build directory
      run: |
        echo "Listing contents of the build directory..."
        ls -l build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build
        publish_branch: gh-pages
        keep_files: false
      env:
        ACTIONS_STEP_DEBUG: true

    - name: Verify Deployment
      run: |
        echo "Deployment complete. Verifying..."
        echo "Visit https://adilad.github.io/ to see the deployed site."
